### ISSUE TITLE
Test summary is enormous

### ISSUE THREAD

**Issue by roji** [Tyrrrz/GitHubActionsTestLogger#14]
### Details

I really like the summary emitted by the test logger. However, will the aggregate statistics (total pass/fail/skip) are great, the test-per-test listing is huge, for projects which have lots of test ([see this as an example](https://github.com/npgsql/npgsql/actions/runs/2306448636)).

I'd suggest showing this collapsed by default (so users click to open it), or possibly to make it opt-in/opt-out in the build (but keep the aggregate statistics!).

**Comment by roji** [comment]
In fact, it seems like loading the build summary page takes a long time because of the amount of tests - note that there's a matrix in the above example with multiple jobs, each executing the full range of tests. An opt-out would be good to have.

**Comment by Tyrrrz** [comment]
Hi @roji.
In the next version, only failed tests will be shown in the summary (and stats for the totals).

**Comment by roji** [comment]
Thanks... It may still make sense to allow accessing detailed information for passing tests (e.g. timing), but ideally that should only be loaded if the user clicks something etc...

**Comment by Tyrrrz** [comment]
> Thanks... It may still make sense to allow accessing detailed information for passing tests (e.g. timing), but ideally that should only be loaded if the user clicks something etc...

I'm still struggling to come up with a good way to organize it. Unfortunately, markdown doesn't offer too many ways to control the layout, and putting too much data tends to result in lots of noise (especially with many collapsible elements).

**Comment by roji** [comment]
Understood - and thanks for the great work regardless.

**Comment by Tyrrrz** [comment]
Hey @roji, can you test out the latest prerelease version? Tell me how well it works for your project

**Comment by roji** [comment]
Sure - should I switch to using [2.0.0-alpha](https://www.nuget.org/packages/GitHubActionsTestLogger/2.0.0-alpha)?

**Comment by Tyrrrz** [comment]
> Sure - should I switch to using [2.0.0-alpha](https://www.nuget.org/packages/GitHubActionsTestLogger/2.0.0-alpha)?

Yup. The only breaking change is that you don't need `report-warnings=false` anymore.

**Comment by roji** [comment]
Thanks, much better!
