### ISSUE TITLE
Expose target framework in annotation format

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/GitHubActionsTestLogger#15]
### Details

Add `$framework`

**Comment by gdziadkiewicz** [comment]
Hi @Tyrrrz
My library has tests running on two different frameworks and currently, I can't tell which test summary corresponds to which framework. Having the framework in the name would help a lot. Are you working on that? If not I'm willing to give it a try.

**Comment by gdziadkiewicz** [comment]
BTW thanks for creating this awesome piece of soft!
