### ISSUE TITLE
Show elapsed time in job summary "summary" instead of "detail"

### ISSUE THREAD

**Issue by adamralph** [Tyrrrz/GitHubActionsTestLogger#17]
### Details

I'd love to be able to see which test suits are taking the longest to run without having to click to expand each section. I.e. instead of this:

![image](https://user-images.githubusercontent.com/677704/172342853-129d944c-d30b-4eb2-b9a0-bea4be8bb1fc.png)

I'd love to see this:

![image](https://user-images.githubusercontent.com/677704/172343655-6e4e5751-47b1-432b-8f02-b867de35bfb5.png)

**Comment by Tyrrrz** [comment]
Hi.

It makes sense, but I wonder if it might become a slipper slope where someone could argue that all other stats should also be moved outside the spoiler. In its current state, the header only contains identifying information about the test suite (name + target framework), while information about the test run itself is below the fold. Balancing signal vs noise in markdown is really hard (due to limited layouting/formatting options) so I felt that this was the best solution for the majority case.

**Comment by adamralph** [comment]
> I wonder if it might become a slipper slope where someone could argue that all other stats should also be moved outside the spoiler

I guess I'm on the slippery slope, so I'll slide to the bottom: why hide anything?

If I look at the test output itself, [this](https://github.com/adamralph/simple-exec/runs/6649806991?check_suite_focus=true#step:4:318) is the interesting line:

> Passed!  - Failed:     0, Passed:    47, Skipped:     1, Total:    48, Duration: 727 ms - /home/runner/work/simple-exec/simple-exec/SimpleExecTests/bin/Release/net6.0/SimpleExecTests.dll (net6.0)

If I were to choose, I would have that line (perhaps formatted slightly nicer) repeated in these job summaries, so I can scroll through them and see everything without having to expand sections with mouse clicks.

**Comment by Tyrrrz** [comment]
Formatting is the hard part :) For repositories with many test suites, having them collapsed at the highest level makes them more visually discernible from each other, especially when multiple test jobs are involved (e.g. different operating systems). I've tried different layouts, and high-level spoilers resulted in the best visual experience.

**Comment by adamralph** [comment]
Fair enough. I guess the general way to solve any such feature request would be a user-specified output template, but I'm not sure if that's feasible.

**Comment by Tyrrrz** [comment]
Yeah, that would be cool. In any case, I do appreciate your suggestion and maybe in a feature major rework of the layout I'll find a way to incorporate it.
