### ISSUE TITLE
Duplicate annotations in build output

### ISSUE THREAD

**Issue by ejsmith** [Tyrrrz/GitHubActionsTestLogger#19]
### Version

2.0

### Details

I am getting duplicate github annotations for build warnings. Any ideas how I can fix them?

Here is a sample output:
https://github.com/exceptionless/Exceptionless/actions/runs/2458030356

### Steps to reproduce

Run build with warnings using this library for output

**Comment by Tyrrrz** [comment]
Do you mean these?

![image](https://user-images.githubusercontent.com/1935960/172614389-f42ae3d5-bdda-497c-aff0-f711cae8230d.png)

These are not produced by GitHubActionsTestLogger, but by dotnet CLI. Maybe you end up running `dotnet build` implicitly explicitly twice?
