### ISSUE TITLE
Specify that a newer Microsoft.NET.Test.Sdk is required!

### ISSUE THREAD

**Issue by Happypig375** [Tyrrrz/GitHubActionsTestLogger#2]
I spent an entire day diagnosing why this package didn't work and found out that
```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
```
is needed instead of the default old version `15.0.0`...

**Comment by Tyrrrz** [comment]
Hey, thanks for letting me know, I wasn't aware of that. I always update all packages to latest when I create a new project.
