### ISSUE TITLE
Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'GitHubActions'.

### ISSUE THREAD

**Issue by lindeberg** [Tyrrrz/GitHubActionsTestLogger#20]
### Version

2.0.1

### Details

.NET 6

The error `Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'GitHubActions'.` is being logged. Tests are outputted to the summary as expected, but I suspect this error is the reason my job is exiting with code 1. 

### Steps to reproduce

- Set up as explained in repo
- Run workflow

**Comment by Tyrrrz** [comment]
Do you have a link to the repo?

**Comment by lindeberg** [comment]
> Do you have a link to the repo?

I figured it out. No bug, as usual..

Accidentally installed test nugets to a wrong (class library) project
