### ISSUE TITLE
Tests fail with exit code 1 when NuGet is not imported in the project.

### ISSUE THREAD

**Issue by jonashendrickx** [Tyrrrz/GitHubActionsTestLogger#24]
### Version

2.3.3

### Platform

.NET 7.0

### Steps to reproduce

      - name: Test with the dotnet CLI
        run: >
          dotnet test
          --no-build
          --configuration Release
          --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"
          --
          RunConfiguration.CollectSourceInformation=true

See: https://github.com/passwordless/passwordless-server/actions/runs/6325650703

### Details

- Expected behavior: If NuGet is not present, make sure tests still pass, but skip the reporting then for that project?

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [X] I have sponsored this project

**Comment by SonicGD** [comment]
Hello. I think your problem is with `dotnet test`, not with this specific package. I suggest you to open issue in [vstest repo](https://github.com/microsoft/vstest).
