### ISSUE TITLE
Option to disable emitting warnings

### ISSUE THREAD

**Issue by roji** [Tyrrrz/GitHubActionsTestLogger#3]
Thanks for a great module!

This currently emits warnings, which is a great thing. Unfortunately, the Github Actions UI for annotations isn't very good, and simply displays warning and error annotations as a big list, without any sorting or grouping. This means that if I have many test skips, I have to scour the list for any errors in between those errors... A good example is [this build](https://github.com/npgsql/efcore.pg/actions/runs/79105476).

Ideally Github will make their UI better (I sent a request on their help/support page), but in the meantime it may be good to provide an option to disable showing warnings altogether. Even without this UI bug, some people are likely not interested in these.

**Comment by roji** [comment]
Another thought is for this logger to output warnings after errors, assuming the Github UI just shows them in-order. But I'm guessing that would require you to store all messages and output them at the very end, which may not be doable etc.

**Comment by Tyrrrz** [comment]
I think it makes sense to silence warnings. Will need to probably extend the logger to accept parameters or something. I'm not too experienced in this, do you have any suggestions how it should be configured?

You're also welcome to submit a PR :)

**Comment by roji** [comment]
Thanks for the quick response... I think I probably have less experience than you in this domain :) If a command-line switch to dotnet test can make its way into your logger, that seems ideal. Otherwise it may be possible for you to look at some property in the csproj, though that doesn't feel like a good solution...

If you look into this and get stuck, I can try to get some guidance from inside Microsoft on how to best go about this.

**Comment by Tyrrrz** [comment]
I believe you can make the logger accept parameters in the form of:

```
dotnet test --logger "GithubActions;ignoreSkippedTests=true"
```

![image](https://user-images.githubusercontent.com/1935960/79856914-a784ea80-83d5-11ea-89c4-368a471699f5.png)

**Comment by Tyrrrz** [comment]
Aha, looks like the parameters are provided in the dictionary if you implement `ITestLoggerWithParameters`:

https://github.com/spekt/xunit.testlogger/blob/49642e2022c0413eb22a86d16dbebd31b9d836d6/src/Xunit.Xml.TestLogger/XunitXmlTestLogger.cs

This seems pretty straightforward. I'll do it after I get some more free time. Otherwise it's open for anyone who wants to submit a PR. 🎉

**Comment by Tyrrrz** [comment]
https://github.com/Tyrrrz/GitHubActionsTestLogger/blob/master/Changelog.md

> Added a switch to disable warnings which are reported if tests were ignored or skipped. Use `--logger "GitHubActions;report-warnings=false"` if you want to do that.

**Comment by roji** [comment]
Thanks, works like a charm!

**Comment by Tyrrrz** [comment]
Enjoy!
