### ISSUE TITLE
Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'GitHubActions'.

### ISSUE THREAD

**Issue by hisuwh** [Tyrrrz/GitHubActionsTestLogger#5]
I'm getting this error `Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'GitHubActions'`

I'm referencing `Microsoft.NET.Test.Sdk` version `16.6.0` which I believe is the latest.

Any tips on how to debug this or what I might be missing?

**Comment by hisuwh** [comment]
The dll doesn't seem to be copied to the bin folder which might be why it cannot detect it.

**Comment by Tyrrrz** [comment]
Just to make sure, are you referencing the nuget package in your test project (i.e. not main project)?

**Comment by hisuwh** [comment]
Yep.  Well actually I'm using a `common.targets` file that my test project is importing.  Though I did try referencing it directly also and that did not work either.

I'm using .net core 2.1 and I see you are using 3 - wonder if that is a factor

**Comment by hisuwh** [comment]
Ok I've created a simple .NET core 3.1 project locally and I am still getting the same error so that does not seem to be relevant.

**Comment by Tyrrrz** [comment]
Does it work if you clone the project I linked and run `dotnet restore` and then `dotnet test -l GitHubActions`?

**Comment by hisuwh** [comment]
ok scrap that I'd missed the import 🤦 
It does work with .net core 3.1.  And I can see it copies the dll to the output.  
So must be something to do with .net core < 3 😞

**Comment by hisuwh** [comment]
This is my test project with .net core 2.1  You can see the reference to your package but it does not copy it to the output folder
![image](https://user-images.githubusercontent.com/4470351/85463394-7fb12f00-b59e-11ea-83ff-3258a3736ca5.png)

So then when I run the tests it does not see the logger

**Comment by Tyrrrz** [comment]
Ahh. I think .NET Core 2.1 apps and lower didn't copy their dependencies to the output folder. It can be enabled with a project property:

```xml
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```

**Comment by hisuwh** [comment]
Just found the exact thing myself 👍 
Tested and that works.  Thanks for your help and quick responses

**Comment by Tyrrrz** [comment]
You're welcome!
