### ISSUE TITLE
Not working when tests run inside a docker container

### ISSUE THREAD

**Issue by PeterKneale** [Tyrrrz/GitHubActionsTestLogger#6]
Thanks for the package - it's just what I was looking for.

Cant seem to get it working when i run my tests in docker-compose on github actions though. Perhaps because the lines are prefixed with the container name in the output?

```
tests_1  | [xUnit.net 00:00:00.77]   Finished:    xxxxx.Tests
tests_1  | 
tests_1  | Test run for /sln/tests/xxxxx/bin/Release/netcoreapp3.1/xxxxx.dll(.NETCoreApp,Version=v3.1)
tests_1  | ::error file=/sln/tests/xxxxx/Demo.cs,line=8::xxxxx.Tests.Demo.This_will_fail: Assert.True() Failure
tests_1  |   X xxxxxxxx.Tests.Demo.This_will_fail [2ms]
tests_1  |   Error Message:
tests_1  |    Assert.True() Failure
tests_1  | Expected: True
tests_1  | Actual:   False
tests_1  |   Stack Trace:
tests_1  |      at xxxxx.Tests.Demo.This_will_fail() in /sln/tests/xxxxx.Tests/Demo.cs:line 8
```

**Comment by Tyrrrz** [comment]
Yeah that's probably the issue.
It uses GH's special format which is `::error ...` so it likely breaks if there's something before it.
I can think of a workaround with custom matchers, but that would be quite a bit of work.
Is it possible to not print the name of the container somehow?

**Comment by adukstad** [comment]
Hi, I know this is closed, but I got this working with the new flag '--no-log-prefix' for docker-compose that was introduced in version [1.28.0](https://github.com/docker/compose/releases/tag/1.28.0) of docker-compose:

**Comment by PeterKneale** [comment]
Good stuff - do you have an example I can see somewhere.
Your use of `--no-log-prefix` fixes the first hurdle but I can see there are a bunch of environment variables we need to now pass through from the agent to the docker container...
Thanks in advance if you have an example

ie:
```cs
public partial class GitHubWorkflow
{
    public static bool IsRunningOnAgent { get; } = string.Equals(
        Environment.GetEnvironmentVariable("GITHUB_ACTIONS"),
        "true",
        StringComparison.OrdinalIgnoreCase
    );

    public static string? SummaryFilePath { get; } =
        Environment.GetEnvironmentVariable("GITHUB_STEP_SUMMARY");

    public static string? TryGenerateFilePermalink(string filePath, int? line = null)
    {
        var serverUrl = Environment.GetEnvironmentVariable("GITHUB_SERVER_URL");
        var repositorySlug = Environment.GetEnvironmentVariable("GITHUB_REPOSITORY");
        var workspacePath = Environment.GetEnvironmentVariable("GITHUB_WORKSPACE");
        var commitHash = Environment.GetEnvironmentVariable("GITHUB_SHA");

       ...
    }
}
```

**Comment by Tyrrrz** [comment]
@PeterKneale Indeed, those environment variables (except `GITHUB_ACTIONS` which may only cause a warning to be issued) are required for the new GitHub job summary feature to work. If you don't care about job summaries, you don't have to pass them.
