### ISSUE TITLE
There is no output from nunit results

### ISSUE THREAD

**Issue by t00** [Tyrrrz/GitHubActionsTestLogger#7]
It seems nunit (possibly xunit) test results are showing only in console as a summary of passed/failed - should any additional output be produced with GitHubActions enabled?

**Comment by Tyrrrz** [comment]
Yes. You should be able to see the errors in the list of annotations and (usually) in commit diff.
You can test the logger locally, it should print messages in the format of:

```
::error foobar::some failed test
```

Additionally, when running locally, it should also print:

```
WARN: Not running inside GitHub Actions, but using GitHub Actions Test Logger.
```

If neither of these are printed, the logger is not enabled.
