### ISSUE TITLE
Working with different paths inside docker based tests

### ISSUE THREAD

**Issue by naphta** [Tyrrrz/GitHubActionsTestLogger#9]
A bit of an interesting issue since it's fair to say I'm not using this tool exactly as would be expected. Essentially we build in docker and test in docker, the problem here is that the file paths don't match the git repo.

What options are there for manipulating those paths which are output? The only way I can think of now is changing the output directories inside the docker container to more closely match the git repository.

**Comment by Tyrrrz** [comment]
Yeah, I can't think of any other way.
